"use client";
import Link from "next/link";
import {Minus,Plus,Trash2,ShoppingBag} from "lucide-react";
import {useCart} from "@/components/cart-provider";
import {products} from "@/data/products";
import {subtotal} from "@/lib/cart";
import {money} from "@/lib/catalog";
import {Bottle} from "@/components/bottle";
export default function CartPage() {const {items,setQuantity,ready}=useCart();return <section className="section page-section"><div className="eyebrow">SUA SELEÇÃO</div><h1>Seu <em>carrinho.</em></h1><p className="demo-notice">Carrinho demonstrativo. Não há pagamento, reserva de estoque ou compra real.</p>{!ready?<p role="status">Carregando seu carrinho…</p>:items.length===0?<div className="empty-cart"><ShoppingBag size={40}/><h2>Uma nova descoberta espera por você.</h2><p>Seu carrinho ainda está vazio.</p><Link className="button gold" href="/catalogo">Explorar coleção →</Link></div>:<div className="cart-layout"><div>{items.map(item=>{const p=products.find(p=>p.id===item.id)!;return <article className="cart-row" key={item.id}><div className="cart-art"><Bottle color={p.color}/></div><div className="cart-info"><Link href={`/produtos/${p.slug}`}><h2>{p.name}</h2></Link><p>{p.volume} · Demonstração</p><span>{money(p.priceCents)} / unidade</span><div className="quantity"><button aria-label={`Diminuir quantidade de ${p.name}`} disabled={item.quantity<=1} onClick={()=>setQuantity(p.id,item.quantity-1)}><Minus size={14}/></button><span aria-label="Quantidade">{item.quantity}</span><button aria-label={`Aumentar quantidade de ${p.name}`} disabled={item.quantity>=99} onClick={()=>setQuantity(p.id,item.quantity+1)}><Plus size={14}/></button></div></div><div className="cart-end"><strong>{money(p.priceCents*item.quantity)}</strong><button aria-label={`Remover ${p.name}`} onClick={()=>setQuantity(p.id,0)}><Trash2 size={17}/></button></div></article>;})}</div><aside className="cart-summary"><h2>Resumo da seleção</h2><div><span>Subtotal</span><strong aria-live="polite">{money(subtotal(items))}</strong></div><p>Valores fictícios para testar a experiência. Frete, pagamentos e checkout serão integrados em uma próxima etapa.</p><Link className="button outline full" href="/catalogo">Continuar explorando</Link></aside></div>}</section>;}
