"use client";
import {catalogMode} from "@/data/products";
import Link from "next/link";
import {useState} from "react";
import {ArrowUpRight, ShoppingBag, Menu, X, MessageCircle} from "lucide-react";
import {useCart} from "./cart-provider";
export function Header() {const {items}=useCart();const [open,setOpen]=useState(false); return <><div className="announcement">UM NOVO CAPÍTULO DA PERFUMARIA ÁRABE <span>·</span> {catalogMode==="demo"?"EXPERIÊNCIA DEMONSTRATIVA":"CATÁLOGO OFICIAL EM PREPARAÇÃO"}</div><header><Link href="/" className="logo" aria-label="Layal Perfumes, início">LAYAL<small>PERFUMES</small></Link><nav className={open?"open":""} aria-label="Navegação principal" onClick={()=>setOpen(false)}><Link href="/catalogo">Coleção</Link><Link href="/catalogo?categoria=masculino">Masculino</Link><Link href="/catalogo?categoria=feminino">Feminino</Link><Link href="/catalogo?categoria=kits">Kits</Link><Link href="/#universo">O universo Layal</Link></nav><div className="header-actions"><Link href="/carrinho" className="bag" aria-label={`Carrinho com ${items.reduce((s,i)=>s+i.quantity,0)} itens`}><ShoppingBag size={20}/><span>{items.reduce((s,i)=>s+i.quantity,0)}</span></Link><button className="mobile-menu" onClick={()=>setOpen(!open)} aria-label={open?"Fechar menu":"Abrir menu"} aria-expanded={open}>{open?<X/>:<Menu/>}</button></div></header></>;}
export function Footer() {const instagram=process.env.NEXT_PUBLIC_INSTAGRAM_URL;const email=process.env.NEXT_PUBLIC_CONTACT_EMAIL;return <footer id="contato"><div className="footer-top"><div><Link href="/" className="logo">LAYAL<small>PERFUMES</small></Link><p>A arte de perfumar. A essência de sentir.</p></div><div><h3>Explore</h3><Link href="/catalogo">Nossa coleção</Link><Link href="/quiz">Encontre seu perfume</Link><Link href="/#universo">Sobre a Layal</Link></div><div><h3>Vamos conversar</h3>{email?<a href={`mailto:${email}`}>{email}</a>:<p>Contato oficial em breve</p>}{instagram?<a href={instagram} target="_blank" rel="noopener noreferrer">Instagram <ArrowUpRight size={13}/></a>:<p>Redes sociais em breve</p>}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Layal Perfumes</span><span>{catalogMode==="demo"?"Catálogo demonstrativo · Nenhuma compra real":"Catálogo oficial · Checkout ainda não disponível"}</span><span>Feito para despertar os sentidos</span></div></footer>;}
export function WhatsApp() {const [open,setOpen]=useState(false);const number=(process.env.NEXT_PUBLIC_WHATSAPP_NUMBER ?? "").replace(/\D/g,"");return <div className="whatsapp">{open&&<div className="contact-popover"><button aria-label="Fechar aviso" onClick={()=>setOpen(false)}><X size={16}/></button><strong>Atendimento Layal</strong><p>Nosso WhatsApp oficial será disponibilizado em breve.</p></div>}{number?<a href={`https://wa.me/${number}`} target="_blank" rel="noopener noreferrer" aria-label="Atendimento pelo WhatsApp"><MessageCircle size={24}/></a>:<button onClick={()=>setOpen(!open)} aria-label="Atendimento pelo WhatsApp" aria-expanded={open}><MessageCircle size={24}/></button>}</div>;}
